### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by michael-hampton** [Laracommerce/laracom#156]
@jsdecena 
If I wanted to add a check on order creation to check the stock of each product and stop the order being saved to the database if there is no stock, what is the nicest way to do this within the repository. I really want to avoid having multiple loops if possible. Do you think a database transaction/rollback would be a good idea? 

Many Thanks # @

**Comment by riteshgautam** [comment]
@jsdecena 
Thank you for creating this amazing Laracommerce.
I have a query,  if we want to update the cart item product price when customer update the quantity on cart page, So In that case,  is it possible to update the price on quantity update in cart?

Looking forward to hearing from you.
Thanks.

**Comment by jsdecena** [comment]
@riteshgautam 

> Thank you for creating this amazing Laracommerce.
I have a query, if we want to update the cart item product price when customer update the quantity on cart page, So In that case, is it possible to update the price on quantity update in cart?

Just to clarify, do you mean that when the admin changes the product price and a customer already has that item on his cart with the previous price, you would like it to be changed as well? 

If that is so, then No. The price is saved in customer's session. Once the user has added the item on their cart, it will stay until payment. It is also **not** a good practice to change the price in the middle of the customer journey since they will feel cheated. Look at it on the real life scenario, you take a product on the shelf for $1 then when you go the cashier and the cashier will say that the real price is $100. How would you feel? Hope it helps!

**Comment by jsdecena** [comment]
@michael-hampton 

> If I wanted to add a check on order creation to check the stock of each product and stop the order being saved to the database if there is no stock, what is the nicest way to do this within the repository. I really want to avoid having multiple loops if possible. Do you think a database transaction/rollback would be a good idea?

Sorry for taking long to respond. Probably, you already have implemented your own idea. For mel, I would do it in the create method of the repository that there is a check to see if the item they are paying is > 0. In laracom, even items that is not yet "paid" (offline bank transfer) are already deducted in the inventory. On this case, every user will have a "reserved" item on thei account until the admin release it back in the inventory. This is good because we will have a history for the user, the product and transaction on what happend on its lifetime in the system. If there is a need to extract this data in the future, we already have the information to provide. :)

**Comment by riteshgautam** [comment]
@jsdecena

Just to clarify, do you mean that when the admin changes the product price and a customer already has that item on his cart with the previous price, you would like it to be changed as well?

 If that is so, then No. The price is saved in customer's session. Once the user has added the item on their cart, it will stay until payment. It is also **not** a good practice to change the price in the middle of the customer journey since they will feel cheated. Look at it on the real life scenario, you take a product on the shelf for $1 then when you go the cashier and the cashier will say that the real price is $100. How would you feel? Hope it helps!

No, I didn't mean, if admin change the price from admin and it need to effect on cart, Actually as per my requirement, I have customized the product attribute section, And I am using the product attribute value only for my requirement not price and other column for now  which are in product_attributes table. 
 
So I am calculating the price like this
final product price = product price * product attribute value * quantity.

or e.g.
Product price is 50$ and attribute value is 10 (I have customized it as per my requirement (10 , 20 , 30 , 40 , 100 and so on..) ) and qty is 1 
then product price is 50 * 10 * 1 = 500$
And in Cart if customer update the Qty  the I need to update price (50 * 10 * 2 = 1000$) like this.

So I have made the changes for it in admin and on product detail page as well when customer  add product to cart from product page. But after adding the product into cart, On cart page customer is updating the quantity, then product product price will also need to update like ( product price + select attribute value * updated quantity ) 
So I need to update the price on cart page as well.

I hope you understand my requirements...

**Comment by jsdecena** [comment]
@riteshgautam Ah, you have to customize the jquery since you are customizing the attributes in the cart. It is a good feature though for others too! So if you have implemented this, you can create a PR so everyone can benefit if they have the same requirement. :)
