### ISSUE TITLE
sir im getting trouble confuse

### ISSUE THREAD

**Issue by mysykez** [Laracommerce/laracom#47]
how to login laracom? in wiki im not see user admin and password

**Comment by romeoenrico** [comment]
HelloAfter db seed You have to use the employee user email and password secret. The First user employee is adminRegards, 


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: Yunan Fajri <notifications@github.com> Data: 20/04/18  08:26  (GMT+01:00) A: Laracommerce/laracom <laracom@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: [Laracommerce/laracom] sir im getting trouble confuse (#47) 
how to login laracom? in wiki im not see user admin and password

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Laracommerce/laracom","title":"Laracommerce/laracom","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Laracommerce/laracom"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"sir im getting trouble confuse (#47)"}],"action":{"name":"View Issue","url":"https://github.com/Laracommerce/laracom/issues/47"}}}

**Comment by romeoenrico** [comment]
Password is secret


Il Ven 20 Apr 2018, 08:26 Yunan Fajri <notifications@github.com> ha scritto:

**Comment by mysykez** [comment]
and email? @romeoenrico

**Comment by belguinan** [comment]
Go to your database and copy and email from employees table,
use it to login into /admin
Password is secret

**Comment by mysykez** [comment]
@belguinan Thanks sir works

**Comment by Wind213** [comment]
make me thinking twice
password is secret.
is actually "secret"
